### ISSUE TITLE
If someone picked your first champ, it will pick a random one.

### ISSUE THREAD

**Issue by Douumm** [tryller/ezbot#11]
I was In queue with someone who picked tristana my first pick before me it just locked in on twisted fate  the first time. The second time it locked on trundle

**Comment by jprzimba** [comment]
it's not a issue it's try first... for second try random if cant pick random get second from secondChampion pick
i'll get another way to pick champions
but now i'm working for garena support

**Comment by igvkip** [comment]
I think it should prioritize owned champions.

**Comment by Douumm** [comment]
Is it possible to add a delay between each account on ezbot before connecting so they dont end up in the same champion select.

**Comment by jprzimba** [comment]
I'm working on champion select to fix all issues just get patience

**Comment by jprzimba** [comment]
Closed.... Ieve mad alot of work on champion select and always have a cance of you pick random champion if someone get your champion first
