### ISSUE TITLE
Ezbot n consegue entrar em fila de baixa prioridade e tem outro erro no arquivo errors.txt

### ISSUE THREAD

**Issue by hstreck** [tryller/ezbot#13]
[errors.txt](https://github.com/tryller/ezbot/files/255592/errors.txt)
[logs.txt](https://github.com/tryller/ezbot/files/255593/logs.txt)

No arquivo logs.txt, encontra erro em hora 5:01 e na hora 10:02. No arquivo errors.txt especifica o erro, só não entendo o que pode ser. Alguém me explica? Erro para entrar na fila de baixa prioridade, isso quer dizer que só dá erro quando eu to em fila de baixa prioridade?

**Comment by jprzimba** [comment]
Low priority queue está funcionando bem tenho várias contas com buster e entra em todas, talvez seja por que você está utilizando multi acocunts. Vou investigar isso.
Sobr eo erro Auth key significa q sua conta/senha está incorreta ou foi banida....

**Comment by hstreck** [comment]
Então cara, eu tentei usar 2 contas, mas n funcionou a segunda. Não entrou em partida na segunda conta, e Authkey n tem sentido pq minhas contas estão certas e não estão banidas >.<

**Comment by jprzimba** [comment]
Auth Key tem um grande problema a ser corrigido , pois o sistema d elogin da riot mudou no 6.8
isso ta dando muita dor de cabeça pra eu arrumar auahuaha
Mas por enquanto to conseguindo rodar 18 horas por dia.. sinal que apesar de tudo erla ainda ta estável tirando os pequenos bugs.

**Comment by hstreck** [comment]
Verdade kkkkkk eu consigo usar ele continuamente agora tranquilamente, baixei novamente, to usando com 2 contas, porém, quando outro invocador picka ashe, o autobuddy não movimenta o campeão escolhido aleatoriamente, creio que isso dê pra arrumar botando uma segunda escolha de champ no arquivo config com seu devido script de skills né? Até agora o único erro é esse, depois de arrumar aquele ali de cima. E outra coisa q eu queria saber, botar o bot pra rodar em normal game da ban né? Tomei ban permanente numa conta lvl baixo pq botei em normal game, mas coop vs ia n dá ban né?

**Comment by jprzimba** [comment]
Esses negocios de ba é relativo vai da sorte auhaa mas em normal ahco q tem mais chance por caua das calls... voce toma mais reportes
