### ISSUE TITLE
EzBot - Accounts Join the Same Game

### ISSUE THREAD

**Issue by Magnuswlange** [tryller/ezbot#14]
Hey Tryller.

Introduction:

I've been using your bot for 2 days now. So far I've had very minor issues. But I noticed this one issue where EzBot makes the accounts join the same game, and therefore one of the accounts picks another champion and goes completely retard for all the time spent botting. 

Workaround:

The workaround I've found for this is to use EzBot with MaxBot=1 and then find a game, close EzBot and LoL, set MaxBot=2 and reopen EzBot, but it's really annoying to do, because you have to do this everytime you wish to pause or stop the bot for whatever reason.

Conclusion:

So EzBot joins the same queue, picks the champion I want it to, and then the second account goes retard. I think you could fix this by adding a delay to the queueing system and I don't think this would be too complicated. For example having the queue code, then sleep for 1-2 minutes and then queue up next account.

Thank you for reading,
Magnus.

**Comment by jprzimba** [comment]
1 - Champion select was reworked now it i'll get champion from 5 configurable champions. it i'll comming with taliah release... I'm waiting for..
2 - Champions joing the same game is too hard to create on difernete games... the unique  method atm is you put bots in different queues for example, MEDIUM_BOT and BEGINNER_BOT
3 - Addding a random delay for login into acocunt maybe...

**Comment by jprzimba** [comment]
Implemented
