### ISSUE TITLE
Suggestion add "username/user" at headbar and progresswindow

### ISSUE THREAD

**Issue by wilpso** [tryller/ezbot#15]
Posted by wilpsa
  1 hour ago, wilpsa said:
Please add some way that we can userlogin/username on "head" EzBot window like "EzBot - Online - User: Riotplayertroll" or some way to we see username inside window at latest progress Update, like
[18/05/2016 18:31:27] In Queue: MEDIUM_BOT as "Riotplayertroll"  << in that teal color yk, would be cool

Pls add both on headbar of EzBot and on progresswindow, thx for the awesome tool

...
on headbar is not good because of ezbot run multi acocunts... it's bug window title ;p
But I can add n Queue: MEDIUM_BOT as "Riotplayertro
but add an issue there https://github.com/tryller/ezbot/issues
I need to remember of
Edited 32 minutes ago by tryller

https://www.elobuddy.net/topic/16118-68-ezbot-auto-queue-v125/?page=19#comment-214239

**Comment by jprzimba** [comment]
Added In Queue: MEDIUM_BOT as "Riotplayertroll"
But progress window what you mean?
