### ISSUE TITLE
Error with summoner names that include non-English letters

### ISSUE THREAD

**Issue by FurkanS1821** [tryller/ezbot#18]
With summoner names that include non-English letters (like ğ,ü,ş,ı,ö,ç,Ğ,Ü,Ş,İ,Ö,Ç), bot will give an error after logging in and won't run. Volibot has the same bug, too.

**Comment by jprzimba** [comment]
hum.... can post screenshoot of error?

**Comment by FurkanS1821** [comment]
![rtdgshfj](https://cloud.githubusercontent.com/assets/15180951/15544462/72bf5bc6-22a1-11e6-9f88-82f57f30d227.jpg)
Translation is: Object reference is not set to an instance of an object.

**Comment by jprzimba** [comment]
It's because of messages that shows your name.. you create an option for not show names tha contains special characters
Thanks for reporting

**Comment by FurkanS1821** [comment]
How can I do that?

**Comment by jprzimba** [comment]
Ops.. i'll create an option for...
