### ISSUE TITLE
Ez bot parou de funcionar

### ISSUE THREAD

**Issue by hahahalol** [tryller/ezbot#2]
Tento deixar o pc ligado a noite toda mas o ezbot para de funcionar e nao upa

**Comment by jprzimba** [comment]
qual erro aparece se possivel pegue os logs de erro na pasta logs. e cole aqui

**Comment by hahahalol** [comment]
não tem esse erro nos logs pois nao aparece nada no console
o ezbot simplesmente para de funcionar mostrando uma mensagem similar a essa: http://www.adaobraga.com.br/wp-content/uploads/2014/05/050614_1746_OInternetEx1.png
agora estou usando o lazy harry botter junto do ezbot, entao se esse erro acontecer o lazy harry botter vai abrir o ezbot novamente, creio eu

**Comment by jprzimba** [comment]
assim fica dificil achar o erro auauahau mas vamos ver o que vai dar deve ser algo com conexao

**Comment by jprzimba** [comment]
Este erro ocorre geralmente quando sua internet oscila de mais /trava ou cai
Fiz varios testes e cheguei a esta conclusao 
No entanto não é um bug de ezBot.
