### ISSUE TITLE
Not starting new game after the 1st

### ISSUE THREAD

**Issue by WSkitzo** [tryller/ezbot#20]
Hello,

I didn't find anyone talking about this issue :(

The 1st game with EzBot goes well. It waits the 5 LeaveBuster minutes, then joins a game.
But after that, it says "Waiting for LeaveBuster time", after 5 mins nothing happens and it keeps stuck on it until i restart EzBot.

So the problem is that I can't let it bot automatically, it's frustrating.

I only have Autobuddy turned on as script.

Any ideas about this?

Thanks!

**Comment by jprzimba** [comment]
Leave buster is working as well
I've alot accounts with buster....
But i'll look into the problem.

**Comment by WSkitzo** [comment]
Hi Tryller,

It has been fixed now, i just had to repair the game :)

Thanks anyways!

**Comment by jprzimba** [comment]
Ok Tanks for reporting back :)
