### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by volks1234** [tryller/ezbot#23]
Japanese server,it logs in says welcome \* my name\* and then instantly crashes saying something " of path riot game/league.../rads/releases.... Idk what is happening http://imgur.com/ZsikrQQ

**Comment by FurkanS1821** [comment]
As I see, bot tries to open up directory League of LegendsRADS/... 

Try adding a "\" at the end to the path in settings.ini
Example:
`LauncherPath=C:\Riot Games\League of Legends\`

**Comment by jprzimba** [comment]
You missing "\" at the end to the path in settings.ini

**Comment by tofy906** [comment]
still not fix the problem for me
