### ISSUE TITLE
Crash program

### ISSUE THREAD

**Issue by miniglikes** [tryller/ezbot#24]
http://i.imgur.com/A5U325u.png i got this error when i try to use ezbot

**Comment by jprzimba** [comment]
Please get log error?
or check your not missing "\" at end of launcherpath in settings file

**Comment by miniglikes** [comment]
if i open error logs its clear but i get error from the screen. its not missing "\" from the launchpath

**Comment by jprzimba** [comment]
whatserver are you trying?

**Comment by miniglikes** [comment]
eune

**Comment by jprzimba** [comment]
Is log file closed while running bot?
if it's open you can get errors

**Comment by miniglikes** [comment]
i open the "errors" but its clear,no any text here.

**Comment by jprzimba** [comment]
Man goto thread and try download latest version

**Comment by miniglikes** [comment]
i try already but didn't work...

**Comment by miniglikes** [comment]
possible to have something not installed or some update?

**Comment by jprzimba** [comment]
.Net Framework 4.5.1 maybe
