### ISSUE TITLE
Change game config fucked up my game 

### ISSUE THREAD

**Issue by volks1234** [tryller/ezbot#26]
I've set up the change game settings to true and set it to 1920x1080 now my screen was fucked up. I  changed the resolution to default and again to true so it changed to a really small screen. After that ingame i set up the game to 1920x1080 and my texts are fucked up. Is there a way to return the screen to its default size? 

Basically change game settings changed my game and i dont know how to fix it. I've used ez bot on only 1 acc but all my accounts are effected. I can fullscreen the game but then the text is fucked up. I submited a ticket on my main acc but I didnt mention it was bcs of ezbot 
![screen21](https://cloud.githubusercontent.com/assets/20041987/16540465/19f0fa94-4066-11e6-8793-6c6e870bc23d.png)
![untitled](https://cloud.githubusercontent.com/assets/20041987/16540479/7ebbb072-4066-11e6-9268-3c9a84974849.png)

EDIT: Tested it again this time i've set it up to be 1280x 960 and its the same as 1980x1080,it's squezed

**Comment by GregerNeger** [comment]
Delete game.cfg file
Then set ReplaceLolConfig to false

**Comment by jprzimba** [comment]
Delete game.cfg file
Then set ReplaceLolConfig to false
