### ISSUE TITLE
champion pick not working

### ISSUE THREAD

**Issue by masterkard** [tryller/ezbot#27]
i write to pick ashe but it's not picking ashe
it says : champion could not be found for championId=0 must be null am i doing something wrong ?
my settings =
[General]
LauncherPath=C:\Riot Games\League of Legends\
MaxBots=30
MaxLevel=30
RandomSpell=false
Spell1=Flash
Spell2=Heal

[Account]
MinDelay=3000
MaxDelay=8500
BuyExpBoost=false

[CHAMPIONS]
FirstChampionPick=ashe
SecondChampionPick=cassiopeia
ThirdChampionPick=yasuo
FourthChampionPick=ezreal
FifthChampionPick=ashe

[LOLScreen]
ReplaceLoLConfig=true
SreenHeight=600
SreenWidth=800
LOWPriority=true

**Comment by jprzimba** [comment]
try last version I never have this issue
