### ISSUE TITLE
"Maximum Bots Running: 1" Won't even start.

### ISSUE THREAD

**Issue by mrdarp** [tryller/ezbot#38]
Every time I try to open the program, it says it's loading accounts, and then it flashes a few text lines, and all I can ever catch is "Maximum Bots Running: 1" then it closes.

So basically I can't get the program to start.

**Comment by jprzimba** [comment]
what ezBotversion are you using because i'm setting my MaxBot to 1 and it works

**Comment by mrdarp** [comment]
It's alright, I got that part fixed a while back and I'm actually not really using ezbot anymore. My smurf I was using it on got permabanned :/ there were some problems where the bot itself would just stand afk at some point on the map, and I had left it running for a while, so apparently it just kind of racked up a bunch of afks in 3v3 bot games and that looked pretty suspicious.

**Comment by jprzimba** [comment]
ezBot can't case any ban
only eb and addons
Issue closed
If you want help create a new one

**Comment by mrdarp** [comment]
Yeah I wasn't asking for help with my ban. I know there's really nothing I can do about that.
