### ISSUE TITLE
as vezes após o client fica com tela preta

### ISSUE THREAD

**Issue by hahahalol** [tryller/ezbot#4]
as vezes o client fica com tela preta e nao carrega (aparecendo a janela de reconectar ou cancelar), fazendo a gente tomar leave buster.

**Comment by jprzimba** [comment]
Não consigo reproduzir este bug aqui.. talve nãos eja do ezbot., talvez seja do eb ou do autoplay
No entanto vou deixa o issue open para ver se consigo reproduzir ele

**Comment by jprzimba** [comment]
Não foi possivel reproduzir... provavelmente bug no autoplay que voce utiliza ou no elobuddy
