### ISSUE TITLE
As soon as the game starts...HELP

### ISSUE THREAD

**Issue by dontmatter12** [tryller/ezbot#40]
When opening the EzBot everything seems to work good upon till the point the game starts. this is what it comes up with. I hate updated the client/ezbot to the latest patch, done everything but still not working.

FIrst time opening ez bot:
http://prnt.sc/c7i6z6

Then when i hit close and reopen i get this:
http://prnt.sc/c7i780

Am I doing something wrong? in the screen shots you can see what scripts i have downloaded for ezbot. So I need anything else? So many questions to ask haha <3

Thanks in advance!

**Comment by jprzimba** [comment]
Missing "\" at LauncherPath at enf of in settings file
