### ISSUE TITLE
Player was attempting to finalize champ select out of turn in game #

### ISSUE THREAD

**Issue by ghost** [tryller/ezbot#44]
Hello today I was setting up my bot accounts( I have 5) and I was setting them up to play on ARAM and I have no clue what the error means but my bots were unable to play.
![untitled](https://cloud.githubusercontent.com/assets/19245988/18221097/2dd33ac4-7147-11e6-8857-69aa094ce2e6.png)

**Comment by ghost** [comment]
Also my path to the league folder is correct!
![untitled1](https://cloud.githubusercontent.com/assets/19245988/18221172/cda08804-7147-11e6-9048-f4dafe0e9972.png)
![untitled2](https://cloud.githubusercontent.com/assets/19245988/18221173/cfc13340-7147-11e6-8c38-733b8013672e.png)

**Comment by Oblivionn** [comment]
They should still run after giving that error message if you wait 2-3 minutes, that shows up every time you're in lobby for aram, as turn 1 is champion selection.
