### ISSUE TITLE
Something really weird

### ISSUE THREAD

**Issue by PomboDev** [tryller/ezbot#45]
Every time i open the bot it connects to the server then it gives me this error

> [02/09/2016 21:31:28] Unable to get Auth Key 
> System.Net.WebException: O servidor remoto retornou um erro: (403) Proibido.
>    em System.Net.HttpWebRequest.GetResponse()
>    em PvPNetClient.PvPNetConnection.GetAuthKey()

And im not banned i dont know what to

**Comment by darvd29** [comment]
I have the same problem here. I have to reset bot a few times to connect with every account because it just randomly does not connect with some accounts with this error.

**Comment by jprzimba** [comment]
Riot chaged his login server and i've no time to find and update ezBot sorry.
