### ISSUE TITLE
weird error+screenshot

### ISSUE THREAD

**Issue by iamdublex** [tryller/ezbot#50]
im having this eror that pops for split of second ,after it ezbot instantly closes https://cloud.githubusercontent.com/assets/22773123/19276482/b5071558-8fd6-11e6-9567-0cb208a23201.png   if i look into logs, i find this error file :  
https://cloud.githubusercontent.com/assets/22773123/19276641/58b40cba-8fd7-11e6-8c56-8075106cc158.png  can somebody please help me as fast as u can?

**Comment by jprzimba** [comment]
Riot changed his login server
I've no time to updte ezBot anymore sorry.
