### ISSUE TITLE
Problems on ezBot startup (patch 6.21.16_10_13_21_40)

### ISSUE THREAD

**Issue by Starzzeh** [tryller/ezbot#51]
So I just downloaded ez bot today, which is a great upgrade from the volibot, but I'm running into some issues on startup. I made sure that I typed all of the correct info into accounts.txt, settings.ini, and version.txt, but when I go to start up the ezBot it will open, and shortly after say "connected at na server" then instantly after, close. (I got lucky to screenshot this in time https://gyazo.com/b65dbaa84db9097ffd543cf326a8fd1c) Any idea what I can do to fix?

**Comment by faresawad** [comment]
^^
i have the same prob .. 100 % the same .. 

i tryed paz bot too .. didnt work eather .. any one can help pls ? :(

**Comment by jprzimba** [comment]
riot changed his login server
Please stop askin about updates
i'll don't update ezBot.

**Comment by faresawad** [comment]
^^
why brother .. we really need u :(( pls
