### ISSUE TITLE
[HELP] EzBot 6.21 crash after first game

### ISSUE THREAD

**Issue by BeWap** [tryller/ezbot#53]
Hi,
I got this problem:
I start EzBot work perfectly for the first game but when it is finish ezbot can't start the second
[
![image](https://cloud.githubusercontent.com/assets/23098917/19766631/3b2df5e6-9c4f-11e6-9e31-b0e40676f140.png)
](url)
Can u help me?

**Comment by FurkanS1821** [comment]
Rito has changed how packets are sent throughout the client, ezbot is outdated and unusable atm.
