### ISSUE TITLE
ezBot disconnects after a time playing with no previous errors.

### ISSUE THREAD

**Issue by lgndz** [tryller/ezbot#6]
[26/04/2016 02:27:52] Waiting leaver buster time: 5 minutes!
[26/04/2016 02:27:52] Launching League of Legends.
[26/04/2016 02:32:52] There was an error in joining lower priority queue.
Disconnecting.
[26/04/2016 02:32:53] Disconnected

> > > No errors in connectivity for the PC ACTUALLY occur during the time this happens.

**Comment by jprzimba** [comment]
what server? i've some acocunts with buster and it work fine

**Comment by lgndz** [comment]
NA server

Sent from Outlook Mobile, please excuse any errors or shorthand.

On Fri, Apr 29, 2016 at 5:32 PM -0700, "Tryller" notifications@github.com wrote:

what server? i've some acocunts with buster and it work fine

**Comment by jprzimba** [comment]
I'll check buster in NA server because of in BR server it's working fine

**Comment by jprzimba** [comment]
Closed tested and it's working but some times it can't enter queue for unknow reason
