### ISSUE TITLE
Crash after starting 

### ISSUE THREAD

**Issue by dovaezburn** [tryller/ezbot#7]
![screenshot_279](https://cloud.githubusercontent.com/assets/18712462/14874752/53cae9d2-0cd1-11e6-8020-cedc6bdcbaa3.png)

this happpens immediately i launch ezbot, i also tried this with harrybotter but no luck. any fixes? i've tried with elobuddy off and on.

**Comment by dovaezburn** [comment]
this also happens with the updated volibot from elobuddy

**Comment by lgndz** [comment]
I get this as well - it only happens occasionally and AFAIK there is no precursor. Sometimes on startup, others after some time

**Comment by dovaezburn** [comment]
![screenshot_280](https://cloud.githubusercontent.com/assets/18712462/14898323/2da1be38-0d54-11e6-92a1-0dfc7236c1d6.png)
got a new error this time

**Comment by jprzimba** [comment]
You missing an "\" at end of LauncherPatch at settings file

**Comment by dovaezburn** [comment]
that might actually fix alot of people's problem, cuz i see people with these errors, wow thanks

**Comment by lgndz** [comment]
testing new version 1.2.5

**Comment by jprzimba** [comment]
working good for me issue closed.
