### ISSUE TITLE
ezBot does not see end game/ start new instance

### ISSUE THREAD

**Issue by lgndz** [tryller/ezbot#9]
Occasionally, ezBot will not see the "Victory" screen and end the LoL instance, causing the bot to hang.

This coder attempted to fix it via work around for example

https://www.elobuddy.net/topic/14768-autoqueue-reloader-fix-for-volibot-pazbot/

**Comment by jprzimba** [comment]
try using an option in you autobuddy... "Auto Close game after ends" or similar
and post results there for me it's working good with this option checks on my autobuddy

**Comment by lgndz** [comment]
Will modify setting on Autobuddy add on after current game and report back. 

Sent from Outlook Mobile, please excuse any errors or shorthand.

On Sat, Apr 30, 2016 at 6:31 AM -0700, "Tryller" notifications@github.com wrote:

try using an option in you autobuddy... "Auto Close game after ends" or similar

and post results there for me it's working good with this option checks on my autobuddy

**Comment by lgndz** [comment]
This is resolved.

I have botted 6+ hours in a row, (much longer then ever achievable before) with ZERO errors whatsoever. No network, no champion selecting, nothing.

I Just restarted the bot to go for another 6+ and will report back however, setting Autobuddy to close game on end has completely solved my issues. Im using ONLY ezBot and no other programs
